# .github/workflows/upload_api.yml
name: Upload API
on:
  repository_dispatch:
    types: [upload_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install InternetArchive Tools
        run: pip install internetarchive

      - name: Upload File
        run: |
          echo "${{ github.event.client_payload.file_data }}" > file.txt
          ia upload "${{ github.event.client_payload.item_id }}" file.txt \
            --access-key "${{ secrets.IA_ACCESS_KEY }}" \
            --secret-key "${{ secrets.IA_SECRET_KEY }}"
