name: Archive.org Upload
on:
  repository_dispatch:
    types: [archive_upload]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install InternetArchive Tools
        run: pip install internetarchive

      - name: Upload to Archive.org
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
        run: |
          ia upload "${{ github.event.client_payload.file_name }}" \
            --access-key "$IA_ACCESS_KEY" \
            --secret-key "$IA_SECRET_KEY" \
            --metadata "title=GitHub ile Yüklendi"
