name: Archive.org Upload
on:
  repository_dispatch:
    types: [trigger_upload]  # JavaScript'te göndereceğiniz event_type ile eşleşmeli

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload to Archive.org
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Token'i environment variable olarak kullan
        run: |
          # Örnek: GitHub API'sini kullanarak bir işlem yap
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"custom_event"}'
